name: Pull Source Files
on: workflow_dispatch
jobs:
  gbPull:
    name: Pull Files
    runs-on: ubuntu-latest
    steps:
    - name: Pull most recent files to local
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SCHOST }}
        username: ${{ secrets.SCUSERNAME }}
        password: ${{ secrets.SCPASSWORD }}
        port: 22
        proxy_host: ${{ secrets.STATHOST }}
        proxy_username: ${{ secrets.SCUSERNAME }}
        proxy_password: ${{ secrets.SCPASSWORD }}
        proxy_port: 22
        script: |
                cd /sciclone/geograd/geoBoundaries/scripts/geoBoundaryBot/geoBoundaryBuilder
                
                echo "" > /sciclone/geograd/geoBoundaries/logs/gbBuilderCron/pullStat
                echo "" > /sciclone/geograd/geoBoundaries/logs/gbBuilderCron/lfsStat
                echo "" > /sciclone/geograd/geoBoundaries/logs/gbBuilderCron/pullJobStat

                qsub pullRun
                
                bash workflow/pullWatch.sh