name: Build CGAZ
on:
  workflow_dispatch:
    branches: [main]
  workflow_run:
    workflows: ["1-Initialize Build"]
    branches: [main]
    types: 
      - completed
jobs:
  buildCGAZ:
    name: Build CGAZ
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Build CGAZ
      uses: appleboy/ssh-action@v0.1.6
      with:
        command_timeout: 360m
        host: ${{ secrets.SCHOST }}
        username: ${{ secrets.SCUSERNAME }}
        password: ${{ secrets.SCPASSWORD }}
        port: 22
        proxy_host: ${{ secrets.STATHOST }}
        proxy_username: ${{ secrets.SCUSERNAME }}
        proxy_password: ${{ secrets.SCPASSWORD }}
        proxy_port: 22
        script: |
                cd /sciclone/geograd/geoBoundaries/scripts/geoBoundaryBot/geoBoundaryBuilder
                echo "" > /sciclone/geograd/geoBoundaries/logs/gbCGAZ/cgazJobStat
                echo "" > /sciclone/geograd/geoBoundaries/logs/gbCGAZ/cgazStat
                qsub cgazBuild          
                bash workflow/cgazWatch.sh