name: Build Country Release Files
on:
  workflow_dispatch:
    branches: [main]
  workflow_run:
    workflows: ["1-Initialize Build"]
    branches: [main]
    types: 
      - completed
jobs:
  buildGBCore:
    name: Build Core Files
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Commence the build
      uses: appleboy/ssh-action@v0.1.6
      with:
        command_timeout: 360m
        host: ${{ secrets.SCHOST }}
        username: ${{ secrets.SCUSERNAME }}
        password: ${{ secrets.SCPASSWORD }}
        port: 22
        proxy_host: ${{ secrets.STATHOST }}
        proxy_username: ${{ secrets.SCUSERNAME }}
        proxy_password: ${{ secrets.SCPASSWORD }}
        proxy_port: 22
        script: |
                cd /sciclone/geograd/geoBoundaries/scripts/geoBoundaryBot/geoBoundaryBuilder
                echo "" > /sciclone/geograd/geoBoundaries/tmp/gbBuilderStage/buildStatus
                echo "" > /sciclone/geograd/geoBoundaries/logs/gbBuilder/buildJobStat
                qsub buildRun               
                bash workflow/buildWatch.sh
                set gbid=`qstat -ru dsmillerrunfol | grep "gbBuilder" | awk '{print $1}'`
                echo $gbid
                qdel $gbid