name: Commit Files and Metadata Build
on:
  workflow_dispatch:
    branches: [main]
  workflow_run:
    workflows: ["Build Country Release Files"]
    branches: [main]
    types: 
      - completed
jobs:
  commitGbCore:
    name: Commit Core Files
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Commit Core Files (LFS) + Build Metadata
      uses: appleboy/ssh-action@v0.1.6
      with:
        command_timeout: 360m
        host: ${{ secrets.SCHOST }}
        username: ${{ secrets.SCUSERNAME }}
        password: ${{ secrets.SCPASSWORD }}
        port: 22
        proxy_host: ${{ secrets.STATHOST }}
        proxy_username: ${{ secrets.SCUSERNAME }}
        proxy_password: ${{ secrets.SCPASSWORD }}
        proxy_port: 22
        script: |
                cd /sciclone/geograd/geoBoundaries/scripts/geoBoundaryBot/geoBoundaryBuilder
                echo "" > /sciclone/geograd/geoBoundaries/logs/gbBuilderCommitCSV/commitStatus
                echo "" > /sciclone/geograd/geoBoundaries/logs/gbBuilder/commitJobStat
                qsub commitBuild             
                bash workflow/commitWatch.sh