name: 3 Push & Update API
on:
  workflow_dispatch:
    branches: [main]
  workflow_run:
    workflows: ["2 Build CGAZ"]
    branches: [main]
    types: 
      - completed
jobs:
  pushUpdates:
    name: Push Updates
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Push Changes
      uses: appleboy/ssh-action@v0.1.6
      with:
        command_timeout: 360m
        host: ${{ secrets.SCHOST }}
        username: ${{ secrets.SCUSERNAME }}
        password: ${{ secrets.SCPASSWORD }}
        port: 22
        proxy_host: ${{ secrets.STATHOST }}
        proxy_username: ${{ secrets.SCUSERNAME }}
        proxy_password: ${{ secrets.SCPASSWORD }}
        proxy_port: 22
        script: |
                echo "" > /sciclone/geograd/geoBoundaries/logs/gbBuilderCommitCSV/pushJobStat
                echo "" > /sciclone/geograd/geoBoundaries/logs/gbBuilderCommitCSV/pushStat
                cd /sciclone/geograd/geoBoundaries/scripts/geoBoundaryBot/geoBoundaryBuilder
                qsub pushBuild          
                bash workflow/pushWatch.sh
  buildAPI:
    name: Build API
    needs: pushUpdates
    runs-on: ubuntu-latest
    steps:
    - name: Build API Locally, Push to Git
      uses: appleboy/ssh-action@v0.1.6
      with:
        command_timeout: 360m
        host: ${{ secrets.SCHOST }}
        username: ${{ secrets.SCUSERNAME }}
        password: ${{ secrets.SCPASSWORD }}
        port: 22
        proxy_host: ${{ secrets.STATHOST }}
        proxy_username: ${{ secrets.SCUSERNAME }}
        proxy_password: ${{ secrets.SCPASSWORD }}
        proxy_port: 22
        script: |
                cd /sciclone/geograd/geoBoundaries/scripts/geoBoundaryBot/geoBoundaryBuilder
                echo "" > /sciclone/geograd/geoBoundaries/logs/gbWeb/apiJobStat
                echo "" > /sciclone/geograd/geoBoundaries/logs/gbWeb/apiStat
                qsub apiBuild          
                bash workflow/apiWatch.sh
  uploadAPI:
    name: Upload API
    needs: buildAPI
    runs-on: ubuntu-latest
    steps:
    - name: Push API to Website
      uses: appleboy/ssh-action@v0.1.6
      with:
        command_timeout: 360m
        host: ${{ secrets.SCHOST }}
        username: ${{ secrets.SCUSERNAME }}
        password: ${{ secrets.SCPASSWORD }}
        port: 22
        proxy_host: ${{ secrets.STATHOST }}
        proxy_username: ${{ secrets.SCUSERNAME }}
        proxy_password: ${{ secrets.SCPASSWORD }}
        proxy_port: 22
        script: |
                cd /sciclone/geograd/geoBoundaries/scripts/geoBoundaryBot/geoBoundaryBuilder
                expect uploadAPI ${{ secrets.GBUSER }} ${{ secrets.GBPASS }} ${{ secrets.GBSERVER }}         
