name: Push Updates
on:
  workflow_dispatch:
    branches: [main]
  workflow_run:
    workflows: ["Build CGAZ Global Release"]
    branches: [main]
    types: 
      - completed
jobs:
  pushUpdates:
    name: Push Updates
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Push Changes
      uses: appleboy/ssh-action@v0.1.6
      with:
        command_timeout: 360m
        host: ${{ secrets.SCHOST }}
        username: ${{ secrets.SCUSERNAME }}
        password: ${{ secrets.SCPASSWORD }}
        port: 22
        proxy_host: ${{ secrets.STATHOST }}
        proxy_username: ${{ secrets.SCUSERNAME }}
        proxy_password: ${{ secrets.SCPASSWORD }}
        proxy_port: 22
        script: |
                cd /sciclone/geograd/geoBoundaries/database/geoBoundaries
                echo "" > /sciclone/geograd/geoBoundaries/logs/gbBuilderCommitCSV/pushJobStat
                echo "" > /sciclone/geograd/geoBoundaries/logs/gbBuilderCommitCSV/pushStat
                git add -A .
                git commit -m "Automated Nightly Build"
                cd /sciclone/geograd/geoBoundaries/scripts/geoBoundaryBot/geoBoundaryBuilder
                qsub pushBuild          
                bash workflow/pushWatch.sh